#!/bin/bash

# Quick debugging script - run after starting location sharing

echo "=========================================="
echo "SCHOOL BUS APP - LOCATION DEBUGGING"
echo "=========================================="
echo ""
echo "Follow these steps:"
echo ""
echo "1️⃣  DRIVER SIDE (on mobile):"
echo "   - Click 'Start Sharing Location'"
echo "   - Look at Logcat for: BUS_ID_FROM_DRIVER=???"
echo "   - WRITE DOWN that Bus ID"
echo ""
echo "2️⃣  PARENT SIDE (on emulator):"
echo "   - Look at Logcat for: busId=???"
echo "   - WRITE DOWN that Bus ID"
echo ""
echo "3️⃣  COMPARE:"
echo "   - Are the Bus IDs the SAME?"
echo ""
echo "4️⃣  IF DIFFERENT:"
echo "   Open Firebase Console → Firestore → students"
echo "   Find the parent's student"
echo "   Check the busId field"
echo "   Make sure driver is assigned to SAME bus"
echo ""
echo "5️⃣  FIREBASE CHECK:"
echo "   Go to Realtime Database"
echo "   Look for /buses/{busId}/lat"
echo "   Should update every 5 seconds"
echo ""
echo "=========================================="
echo "COMMON ISSUES & FIXES:"
echo "=========================================="
echo ""
echo "❌ onDataChange not called"
echo "   → Check Realtime DB rules allow .read"
echo ""
echo "❌ Lat/Lng are null"
echo "   → Driver didn't write yet (wait 5 sec)"
echo "   → Or Bus ID mismatch"
echo ""
echo "❌ Firebase update failed: Permission denied"
echo "   → Fix Realtime DB rules (see docs)"
echo ""
echo "=========================================="

